/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest ingredient names
         * @description Type-ahead for the recipe form: names starting with the text first, then names containing it.
         */
        get: operations["suggest_ingredients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixed lists for forms and filters */
        get: operations["get_options"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a week's plan
         * @description Monday to Sunday with each day's meals in order. `week` can be any date in the week; defaults to today.
         */
        get: operations["get_week"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Days with meals in a month
         * @description For the calendar picker's dots.
         */
        get: operations["planned_days"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a meal to a day
         * @description The meal goes last on that day. Unlimited meals per day.
         */
        post: operations["add_entry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a meal from the plan */
        delete: operations["delete_entry"];
        options?: never;
        head?: never;
        /**
         * Change a planned meal
         * @description Change servings, swap the recipe, move it to another day (goes last there) or reorder it within its day.
         */
        patch: operations["update_entry"];
        trace?: never;
    };
    "/api/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dietary preferences */
        get: operations["get_preferences"];
        /**
         * Set dietary preferences
         * @description Replaces the saved dietary labels. The recipe list filters by these by default.
         */
        put: operations["update_preferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get profile */
        get: operations["get_profile"];
        /**
         * Update profile
         * @description Name, email and household size (the default servings when adding a meal). Profile only, no login.
         */
        put: operations["update_profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recipes (paged)
         * @description Search and filter recipes, one page at a time (ordered by name). Dietary filter defaults to the saved preferences unless `dietary` is given or `all=true`. Dietary labels must **all** match (vegetarian also accepts vegan); meal types and tags match **any**. Search covers recipe names and ingredients. A page past the end returns no items with the correct `total`.
         */
        get: operations["list_recipes"];
        put?: never;
        /**
         * Create a recipe
         * @description Adds a custom recipe. Unknown tag names are created. The slug is made from the name.
         */
        post: operations["create_recipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a recipe
         * @description Full recipe. Pass `servings` to scale ingredient amounts.
         */
        get: operations["get_recipe"];
        /**
         * Update a recipe
         * @description Replaces a custom recipe. Built-in recipes are read-only. Renaming updates the slug.
         */
        put: operations["update_recipe"];
        post?: never;
        /**
         * Delete a recipe
         * @description Soft-deletes a custom recipe: removed from today and future days, kept in past weeks.
         */
        delete: operations["delete_recipe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{slug}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count upcoming planned meals
         * @description Used by the delete confirmation: how many meals from today onwards use this recipe.
         */
        get: operations["recipe_usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags */
        get: operations["list_tags"];
        put?: never;
        /**
         * Create a tag
         * @description Returns the existing tag if one with the same key already exists (e.g. `Low cost` / `low-cost`).
         */
        post: operations["create_tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Units for the ingredient unit dropdown */
        get: operations["list_units"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Cuisine
         * @description Fixed list; every recipe has exactly one. "other" covers anything not listed.
         * @enum {string}
         */
        Cuisine: "british" | "chinese" | "indian" | "italian" | "mediterranean" | "mexican" | "thai" | "other";
        /**
         * DietaryLabel
         * @description Fixed list used for filtering. A recipe has zero or more.
         * @enum {string}
         */
        DietaryLabel: "vegetarian" | "vegan" | "gluten-free" | "dairy-free";
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /** Requestid */
            requestId: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** IngredientLine */
        IngredientLine: {
            /** Ingredientid */
            ingredientId: number;
            /** Item */
            item: string;
            /** Prep */
            prep?: string | null;
            /** Quantity */
            quantity: number | null;
            /** Unit */
            unit: string | null;
        };
        /** IngredientLineIn */
        IngredientLineIn: {
            /** Item */
            item: string;
            /** Prep */
            prep?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Unit */
            unit?: string | null;
        };
        /**
         * IngredientSuggestion
         * @description ASSUMPTION (1): GET /api/ingredients?q= returns matching ingredient names for the form.
         */
        IngredientSuggestion: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * MealType
         * @description What a recipe suits. A recipe has one or more; used as a filter (the plan has no fixed slots).
         * @enum {string}
         */
        MealType: "breakfast" | "lunch" | "dinner" | "dessert";
        /**
         * OptionsOut
         * @description GET /api/options: the fixed lists, typed as enums so clients get exact values.
         */
        OptionsOut: {
            /** Cuisines */
            cuisines: components["schemas"]["Cuisine"][];
            /** Dietarylabels */
            dietaryLabels: components["schemas"]["DietaryLabel"][];
            /** Mealtypes */
            mealTypes: components["schemas"]["MealType"][];
        };
        /** PlanDayOut */
        PlanDayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Entries */
            entries: components["schemas"]["PlanEntryOut"][];
        };
        /**
         * PlanDaysOut
         * @description GET /api/plan/days?month=YYYY-MM: days with meals, for the calendar dots.
         */
        PlanDaysOut: {
            /** Dates */
            dates: string[];
            /** Month */
            month: string;
        };
        /**
         * PlanEntryCreate
         * @description POST /api/plan/entries. The meal goes last on that day.
         */
        PlanEntryCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Recipeid
             * Format: uuid
             */
            recipeId: string;
            /** Servings */
            servings: number;
        };
        /** PlanEntryOut */
        PlanEntryOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Recipedeleted */
            recipeDeleted: boolean;
            /**
             * Recipeid
             * Format: uuid
             */
            recipeId: string;
            /** Recipename */
            recipeName: string;
            /** Recipeslug */
            recipeSlug: string;
            /** Servings */
            servings: number;
        };
        /**
         * PlanEntryUpdate
         * @description PATCH /api/plan/entries/{id}: change servings, swap recipe, move day or reorder.
         */
        PlanEntryUpdate: {
            /** Date */
            date?: string | null;
            /** Position */
            position?: number | null;
            /** Recipeid */
            recipeId?: string | null;
            /** Servings */
            servings?: number | null;
        };
        /** PreferencesIn */
        PreferencesIn: {
            /**
             * Dietary
             * @default []
             */
            dietary?: components["schemas"]["DietaryLabel"][];
        };
        /** PreferencesOut */
        PreferencesOut: {
            /** Dietary */
            dietary: components["schemas"]["DietaryLabel"][];
        };
        /** ProfileIn */
        ProfileIn: {
            /** Email */
            email?: string | null;
            /** Householdsize */
            householdSize?: number | null;
            /** Name */
            name?: string | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Email */
            email: string | null;
            /** Householdsize */
            householdSize: number | null;
            /** Name */
            name: string | null;
        };
        /**
         * RecipeCreate
         * @description POST /api/recipes and PUT /api/recipes/{id} (custom recipes only).
         */
        RecipeCreate: {
            cuisine: components["schemas"]["Cuisine"];
            /**
             * Dietary
             * @default []
             */
            dietary?: components["schemas"]["DietaryLabel"][];
            /** Ingredients */
            ingredients: components["schemas"]["IngredientLineIn"][];
            /** Mealtypes */
            mealTypes: components["schemas"]["MealType"][];
            /** Method */
            method: string[];
            /** Name */
            name: string;
            /** Serves */
            serves: number;
            /**
             * Tags
             * @default []
             */
            tags?: string[];
        };
        /**
         * RecipeDetail
         * @description GET /api/recipes/{id}?servings=N. Quantities are scaled when servings is given.
         */
        RecipeDetail: {
            cuisine: components["schemas"]["Cuisine"];
            /** Defaultimage */
            defaultImage: string;
            /** Dietary */
            dietary: components["schemas"]["DietaryLabel"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Imageurl */
            imageUrl: string | null;
            /** Ingredients */
            ingredients: components["schemas"]["IngredientLine"][];
            /** Iscustom */
            isCustom: boolean;
            /** Mealtypes */
            mealTypes: components["schemas"]["MealType"][];
            /** Method */
            method: string[];
            /** Name */
            name: string;
            /** Serves */
            serves: number;
            /** Servings */
            servings: number;
            /** Slug */
            slug: string;
            /** Tags */
            tags: components["schemas"]["TagOut"][];
        };
        /**
         * RecipePage
         * @description GET /api/recipes: one page of results. A page past the end has no items but the right totals.
         */
        RecipePage: {
            /** Items */
            items: components["schemas"]["RecipeSummary"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
            /** Totalpages */
            totalPages: number;
        };
        /**
         * RecipeSummary
         * @description GET /api/recipes item.
         */
        RecipeSummary: {
            cuisine: components["schemas"]["Cuisine"];
            /** Defaultimage */
            defaultImage: string;
            /** Dietary */
            dietary: components["schemas"]["DietaryLabel"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Imageurl */
            imageUrl: string | null;
            /** Iscustom */
            isCustom: boolean;
            /** Mealtypes */
            mealTypes: components["schemas"]["MealType"][];
            /** Name */
            name: string;
            /** Serves */
            serves: number;
            /** Slug */
            slug: string;
            /** Tags */
            tags: components["schemas"]["TagOut"][];
        };
        /**
         * RecipeUsageOut
         * @description ASSUMPTION (3): GET /api/recipes/{id}/usage -> {"upcomingMeals": N} for the delete confirmation.
         */
        RecipeUsageOut: {
            /** Upcomingmeals */
            upcomingMeals: number;
        };
        /** ShoppingListChangesOut */
        ShoppingListChangesOut: {
            /** Added */
            added: number;
            /** Changed */
            changed: number;
            /** Removed */
            removed: number;
        };
        /** ShoppingListItemOut */
        ShoppingListItemOut: {
            /** Id */
            id: number;
            /** Ingredientid */
            ingredientId: number;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number | null;
            /** Ticked */
            ticked: boolean;
            /** Totaste */
            toTaste: boolean;
            /** Unit */
            unit: string;
            /** Usedin */
            usedIn: string[];
        };
        /**
         * ShoppingListOut
         * @description GET /api/shopping-list?week=YYYY-MM-DD.
         */
        ShoppingListOut: {
            changes: components["schemas"]["ShoppingListChangesOut"] | null;
            /** Items */
            items: components["schemas"]["ShoppingListItemOut"][];
            /**
             * Weekstart
             * Format: date
             */
            weekStart: string;
        };
        /**
         * ShoppingTickIn
         * @description PATCH /api/shopping-list/items/{id}.
         */
        ShoppingTickIn: {
            /** Ticked */
            ticked: boolean;
        };
        /**
         * TagIn
         * @description POST /api/tags (the recipe form can also send new tag names directly).
         */
        TagIn: {
            /** Name */
            name: string;
        };
        /** TagOut */
        TagOut: {
            /** Isbuiltin */
            isBuiltin: boolean;
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /** UnitOut */
        UnitOut: {
            /** Group */
            group: string;
            /** Key */
            key: string | null;
            /** Label */
            label: string;
        };
        /**
         * WeekPlanOut
         * @description GET /api/plan?week=YYYY-MM-DD (any date in the week; defaults to this week).
         */
        WeekPlanOut: {
            /** Days */
            days: components["schemas"]["PlanDayOut"][];
            /**
             * Weekstart
             * Format: date
             */
            weekStart: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    suggest_ingredients: {
        parameters: {
            query: {
                /** @description Text typed so far */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientSuggestion"][];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionsOut"];
                };
            };
        };
    };
    get_week: {
        parameters: {
            query?: {
                /** @description Any date in the week (YYYY-MM-DD) */
                week?: string | null;
                /** @description The user's local date (YYYY-MM-DD). Defaults to the server's local date. */
                today?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekPlanOut"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    planned_days: {
        parameters: {
            query: {
                /** @description YYYY-MM */
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDaysOut"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_entry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanEntryOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plan entry id */
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plan entry id */
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanEntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanEntryOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
        };
    };
    update_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    update_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_recipes: {
        parameters: {
            query?: {
                /** @description Search text (name or ingredient) */
                q?: string | null;
                /** @description Comma-separated, e.g. `lunch,dinner` */
                mealType?: string | null;
                /** @description Comma-separated, e.g. `vegetarian,gluten-free` */
                dietary?: string | null;
                /** @description Comma-separated tag keys, e.g. `quick,low-cost` */
                tag?: string | null;
                /** @description Ignore saved dietary preferences */
                all?: boolean;
                /** @description Page number, starting at 1 */
                page?: number;
                /** @description Recipes per page */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipePage"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_recipe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
            /** @description Conflict (e.g. a recipe with this name already exists) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_recipe: {
        parameters: {
            query?: {
                /** @description Scale amounts to this many servings */
                servings?: number | null;
            };
            header?: never;
            path: {
                /** @description Recipe slug, e.g. `lentil-dahl` */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_recipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Recipe slug, e.g. `lentil-dahl` */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
            /** @description Not allowed (e.g. editing a built-in recipe) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict (e.g. a recipe with this name already exists) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_recipe: {
        parameters: {
            query?: {
                /** @description The user's local date (YYYY-MM-DD). Defaults to the server's local date. */
                today?: string | null;
            };
            header?: never;
            path: {
                /** @description Recipe slug, e.g. `lentil-dahl` */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not allowed (e.g. editing a built-in recipe) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recipe_usage: {
        parameters: {
            query?: {
                /** @description The user's local date (YYYY-MM-DD). Defaults to the server's local date. */
                today?: string | null;
            };
            header?: never;
            path: {
                /** @description Recipe slug, e.g. `lentil-dahl` */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeUsageOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_tags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
        };
    };
    create_tag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation error: `details.fields` maps each field to a message */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_units: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitOut"][];
                };
            };
        };
    };
}
