/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Cuisine
         * @description Fixed list; every recipe has exactly one. "other" covers anything not listed.
         * @enum {string}
         */
        Cuisine: "british" | "chinese" | "indian" | "italian" | "mediterranean" | "mexican" | "thai" | "other";
        /**
         * DietaryLabel
         * @description Fixed list used for filtering. A recipe has zero or more.
         * @enum {string}
         */
        DietaryLabel: "vegetarian" | "vegan" | "gluten-free" | "dairy-free";
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /**
             * Details
             * @default null
             */
            details: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /** Requestid */
            requestId: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** IngredientLine */
        IngredientLine: {
            /** Ingredientid */
            ingredientId: number;
            /** Item */
            item: string;
            /**
             * Prep
             * @default null
             */
            prep: string | null;
            /** Quantity */
            quantity: number | null;
            /** Unit */
            unit: string | null;
        };
        /** IngredientLineIn */
        IngredientLineIn: {
            /** Item */
            item: string;
            /**
             * Prep
             * @default null
             */
            prep: string | null;
            /**
             * Quantity
             * @default null
             */
            quantity: number | null;
            /**
             * Unit
             * @default null
             */
            unit: string | null;
        };
        /**
         * IngredientSuggestion
         * @description ASSUMPTION (1): GET /api/ingredients?q= returns matching ingredient names for the form.
         */
        IngredientSuggestion: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * MealType
         * @description What a recipe suits. A recipe has one or more; used as a filter (the plan has no fixed slots).
         * @enum {string}
         */
        MealType: "breakfast" | "lunch" | "dinner" | "dessert";
        /** OptionsOut */
        OptionsOut: {
            /**
             * Cuisines
             * @default [
             *       "british",
             *       "chinese",
             *       "indian",
             *       "italian",
             *       "mediterranean",
             *       "mexican",
             *       "thai",
             *       "other"
             *     ]
             */
            cuisines: string[];
            /**
             * Dietarylabels
             * @default [
             *       "vegetarian",
             *       "vegan",
             *       "gluten-free",
             *       "dairy-free"
             *     ]
             */
            dietaryLabels: string[];
            /**
             * Mealtypes
             * @default [
             *       "breakfast",
             *       "lunch",
             *       "dinner",
             *       "dessert"
             *     ]
             */
            mealTypes: string[];
        };
        /** PlanDayOut */
        PlanDayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Entries */
            entries: components["schemas"]["PlanEntryOut"][];
        };
        /**
         * PlanDaysOut
         * @description GET /api/plan/days?month=YYYY-MM: days with meals, for the calendar dots.
         */
        PlanDaysOut: {
            /** Dates */
            dates: string[];
            /** Month */
            month: string;
        };
        /**
         * PlanEntryCreate
         * @description POST /api/plan/entries. The meal goes last on that day.
         */
        PlanEntryCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Recipeid
             * Format: uuid
             */
            recipeId: string;
            /** Servings */
            servings: number;
        };
        /** PlanEntryOut */
        PlanEntryOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Recipedeleted */
            recipeDeleted: boolean;
            /**
             * Recipeid
             * Format: uuid
             */
            recipeId: string;
            /** Recipename */
            recipeName: string;
            /** Recipeslug */
            recipeSlug: string;
            /** Servings */
            servings: number;
        };
        /**
         * PlanEntryUpdate
         * @description PATCH /api/plan/entries/{id}: change servings, swap recipe, move day or reorder.
         */
        PlanEntryUpdate: {
            /**
             * Date
             * @default null
             */
            date: string | null;
            /**
             * Position
             * @default null
             */
            position: number | null;
            /**
             * Recipeid
             * @default null
             */
            recipeId: string | null;
            /**
             * Servings
             * @default null
             */
            servings: number | null;
        };
        /** PreferencesIn */
        PreferencesIn: {
            /**
             * Dietary
             * @default []
             */
            dietary: components["schemas"]["DietaryLabel"][];
        };
        /** PreferencesOut */
        PreferencesOut: {
            /** Dietary */
            dietary: components["schemas"]["DietaryLabel"][];
        };
        /** ProfileIn */
        ProfileIn: {
            /**
             * Email
             * @default null
             */
            email: string | null;
            /**
             * Householdsize
             * @default null
             */
            householdSize: number | null;
            /**
             * Name
             * @default null
             */
            name: string | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Email */
            email: string | null;
            /** Householdsize */
            householdSize: number | null;
            /** Name */
            name: string | null;
        };
        /**
         * RecipeCreate
         * @description POST /api/recipes and PUT /api/recipes/{id} (custom recipes only).
         */
        RecipeCreate: {
            cuisine: components["schemas"]["Cuisine"];
            /**
             * Dietary
             * @default []
             */
            dietary: components["schemas"]["DietaryLabel"][];
            /** Ingredients */
            ingredients: components["schemas"]["IngredientLineIn"][];
            /** Mealtypes */
            mealTypes: components["schemas"]["MealType"][];
            /** Method */
            method: string[];
            /** Name */
            name: string;
            /** Serves */
            serves: number;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /**
         * RecipeDetail
         * @description GET /api/recipes/{id}?servings=N. Quantities are scaled when servings is given.
         */
        RecipeDetail: {
            cuisine: components["schemas"]["Cuisine"];
            /** Defaultimage */
            defaultImage: string;
            /** Dietary */
            dietary: components["schemas"]["DietaryLabel"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Imageurl */
            imageUrl: string | null;
            /** Ingredients */
            ingredients: components["schemas"]["IngredientLine"][];
            /** Iscustom */
            isCustom: boolean;
            /** Mealtypes */
            mealTypes: components["schemas"]["MealType"][];
            /** Method */
            method: string[];
            /** Name */
            name: string;
            /** Serves */
            serves: number;
            /** Servings */
            servings: number;
            /** Slug */
            slug: string;
            /** Tags */
            tags: components["schemas"]["TagOut"][];
        };
        /**
         * RecipeSummary
         * @description GET /api/recipes item.
         */
        RecipeSummary: {
            cuisine: components["schemas"]["Cuisine"];
            /** Defaultimage */
            defaultImage: string;
            /** Dietary */
            dietary: components["schemas"]["DietaryLabel"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Imageurl */
            imageUrl: string | null;
            /** Iscustom */
            isCustom: boolean;
            /** Mealtypes */
            mealTypes: components["schemas"]["MealType"][];
            /** Name */
            name: string;
            /** Serves */
            serves: number;
            /** Slug */
            slug: string;
            /** Tags */
            tags: components["schemas"]["TagOut"][];
        };
        /**
         * RecipeUsageOut
         * @description ASSUMPTION (3): GET /api/recipes/{id}/usage -> {"upcomingMeals": N} for the delete confirmation.
         */
        RecipeUsageOut: {
            /** Upcomingmeals */
            upcomingMeals: number;
        };
        /** ShoppingListChangesOut */
        ShoppingListChangesOut: {
            /** Added */
            added: number;
            /** Changed */
            changed: number;
            /** Removed */
            removed: number;
        };
        /** ShoppingListItemOut */
        ShoppingListItemOut: {
            /** Id */
            id: number;
            /** Ingredientid */
            ingredientId: number;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number | null;
            /** Ticked */
            ticked: boolean;
            /** Totaste */
            toTaste: boolean;
            /** Unit */
            unit: string;
            /** Usedin */
            usedIn: string[];
        };
        /**
         * ShoppingListOut
         * @description GET /api/shopping-list?week=YYYY-MM-DD.
         */
        ShoppingListOut: {
            changes: components["schemas"]["ShoppingListChangesOut"] | null;
            /** Items */
            items: components["schemas"]["ShoppingListItemOut"][];
            /**
             * Weekstart
             * Format: date
             */
            weekStart: string;
        };
        /**
         * ShoppingTickIn
         * @description PATCH /api/shopping-list/items/{id}.
         */
        ShoppingTickIn: {
            /** Ticked */
            ticked: boolean;
        };
        /**
         * TagIn
         * @description POST /api/tags (the recipe form can also send new tag names directly).
         */
        TagIn: {
            /** Name */
            name: string;
        };
        /** TagOut */
        TagOut: {
            /** Isbuiltin */
            isBuiltin: boolean;
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /** UnitOut */
        UnitOut: {
            /** Group */
            group: string;
            /** Key */
            key: string | null;
            /** Label */
            label: string;
        };
        /**
         * WeekPlanOut
         * @description GET /api/plan?week=YYYY-MM-DD (any date in the week; defaults to this week).
         */
        WeekPlanOut: {
            /** Days */
            days: components["schemas"]["PlanDayOut"][];
            /**
             * Weekstart
             * Format: date
             */
            weekStart: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
